"""
Django settings for scriptura_api project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from urllib.parse import quote, unquote
from dotenv import load_dotenv

# Load environment variables from .env file (two levels up from this file)
load_dotenv(Path(__file__).resolve().parent.parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

_base_allowed_hosts = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]
ALLOWED_HOSTS = _base_allowed_hosts + ['testserver', '.vercel.app']

VERCEL_URL = os.getenv('VERCEL_URL', '').strip()
if VERCEL_URL:
    ALLOWED_HOSTS.append(VERCEL_URL)

# Remove duplicates while preserving order
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django_filters',
    'core',
    'analytics',
    'themes',
    'ingestion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'scriptura_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scriptura_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL', '')
IS_VERCEL = os.getenv('VERCEL', '') == '1'
DB_CONN_MAX_AGE = int(os.getenv('DB_CONN_MAX_AGE', '0' if IS_VERCEL else '600'))


def _normalize_database_url_password(url: str) -> str:
    """
    Normalize DATABASE_URL by safely URL-encoding password portion when needed.
    Handles URLs like: postgresql://user:raw@pass@host:5432/db
    by splitting at the last '@' (credentials separator).
    """
    if '://' not in url or '@' not in url:
        return url

    scheme, rest = url.split('://', 1)
    if '@' not in rest:
        return url

    creds, host_part = rest.rsplit('@', 1)
    if ':' not in creds:
        return url

    username, password = creds.split(':', 1)
    safe_password = quote(unquote(password), safe='')
    return f'{scheme}://{username}:{safe_password}@{host_part}'

if DATABASE_URL:
    parsed_db_config = None
    try:
        parsed_db_config = dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=DB_CONN_MAX_AGE,
            ssl_require=os.getenv('DB_SSL_REQUIRE', 'True') == 'True',
        )
    except dj_database_url.ParseError:
        normalized_database_url = _normalize_database_url_password(DATABASE_URL)
        parsed_db_config = dj_database_url.parse(
            normalized_database_url,
            conn_max_age=DB_CONN_MAX_AGE,
            ssl_require=os.getenv('DB_SSL_REQUIRE', 'True') == 'True',
        )

    DATABASES = {
        'default': parsed_db_config
    }
    # Recommended when using Supabase transaction pooler / PgBouncer.
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# REST framework defaults: pagination, filtering and search all enabled
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 50,  # Reduced from 100 for faster responses
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [],
    # versioning can be added later (NamespaceVersioning, etc.)
}

# drf-spectacular configuration for automatic OpenAPI schema
SPECTACULAR_SETTINGS = {
    'TITLE': 'Scriptura API',
    'VERSION': '1.0.0',
    'DESCRIPTION': (
        '## Scriptura Bible Analytics API\n\n'
        'A REST API for the Douay-Rheims Bible with full-text search, thematic analytics, '
        'lexical similarity graphs, and user-curated verse collections.\n\n'
        '### Authentication\n'
        'Most read endpoints are **public** (no token required). '
        'Write operations on collections require a **JWT Bearer token**.\n\n'
        '**How to authenticate here:**\n'
        '1. Sign in via the main app at `/` to receive your `access` token. '
        'Copy it from browser DevTools → Application → Local Storage → `access_token`, '
        'or call `POST /api/auth/google-token/` directly with a Google `id_token`.\n'
        '2. Click the **Authorize 🔒** button at the top of this page.\n'
        '3. In the **bearerAuth (http, Bearer)** field paste your access token and click Authorize.\n\n'
        'Tokens expire after **1 hour**. Refresh via `POST /api/auth/token/refresh/`.'
    ),
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [{'bearerAuth': []}],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'displayRequestDuration': True,
        'filter': True,
        'tryItOutEnabled': True,
        'defaultModelsExpandDepth': 1,
    },
    'SCHEMA_PATH_PREFIX': r'/api/',
    'SECURITY_DEFINITIONS': {
        'bearerAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
            'description': 'Paste your JWT access token here (without the "Bearer " prefix).',
        }
    },
}

# CORS configuration for frontend
_default_cors_origins = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

_env_cors_origins = [
    origin.strip()
    for origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]

CORS_ALLOWED_ORIGINS = _env_cors_origins or _default_cors_origins

if VERCEL_URL:
    CORS_ALLOWED_ORIGINS.append(f"https://{VERCEL_URL}")

CORS_ALLOWED_ORIGINS = list(dict.fromkeys(CORS_ALLOWED_ORIGINS))
CORS_ALLOW_CREDENTIALS = True

_env_csrf_origins = [
    origin.strip()
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
CSRF_TRUSTED_ORIGINS = _env_csrf_origins
if VERCEL_URL:
    CSRF_TRUSTED_ORIGINS.append(f"https://{VERCEL_URL}")
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

# Trust Vercel's forwarded proto header for correct https detection.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Google Identity Services uses a popup flow that needs opener access to
# communicate the credential back to the main window.
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

# Google OAuth client id used to verify Google-issued id_token on /api/auth/google-token/
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SimpleJWT configuration
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}
