# Generated by Django 4.2.28 on 2026-03-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='order',
        ),
        migrations.AlterField(
            model_name='book',
            name='testament',
            field=models.CharField(max_length=10),
        ),
    ]
