# Generated by Django 4.2.28 on 2026-03-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_book_order_alter_book_testament'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='paragraph_start',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_verse', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.chapter')),
            ],
            options={
                'ordering': ['start_verse', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.CharField(blank=True, default='', max_length=20)),
                ('text', models.TextField()),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footnotes', to='core.verse')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
