# Generated by Django 4.2.28 on 2026-03-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
        ('core', '0003_verse_paragraph_start_section_footnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('themes', models.ManyToManyField(blank=True, related_name='collections', to='themes.theme')),
                ('verses', models.ManyToManyField(blank=True, related_name='collections', to='core.verse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
