# Generated by Django 4.2.28 on 2026-03-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_collection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='themes',
        ),
    ]
