# Generated by Django 4.2.28 on 2026-03-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_drop_legacy_auth_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, this collection is visible to all users.'),
        ),
    ]
