# Generated by Django 4.2.28 on 2026-03-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_book_order_alter_book_testament'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('entropy', models.FloatField(blank=True, null=True)),
                ('ttr', models.FloatField(blank=True, null=True)),
                ('hapax_count', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='core.book')),
            ],
        ),
    ]
