# Generated by Django 4.2.28 on 2026-03-04 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeCoverageCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_signature', models.CharField(max_length=64)),
                ('coverage', models.JSONField(default=list)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('theme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_cache', to='themes.theme')),
            ],
        ),
    ]
