# Generated by Django 4.2.28 on 2026-03-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_themecoveragecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_set_hash', models.CharField(max_length=64)),
                ('metric', models.CharField(max_length=32)),
                ('threshold', models.FloatField()),
                ('graph_data', models.JSONField(default=dict)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('book_set_hash', 'metric', 'threshold')},
            },
        ),
    ]
